---
config:
  layout: elk
---
stateDiagram
    direction TB

    %% Define States
    state "Chase init (200)" as ChaseInit
    state "Chase rotate to ball (201)" as ChaseRotate
    state "Chase move to ball (202)" as ChaseMove
    state "Chase kick ball (203)" as ChaseKick
    state "Chase done (299)" as ChaseDone


    %% Transitions
    [*] --> Init
    ChaseInit --> ChaseRotate: enter chase mode

    ChaseRotate --> ChaseMove: facing ball achieved
    ChaseRotate --> ChaseDone: lost
    ChaseRotate --> ChaseRotate: not facing ball yet

    %% MOVE_TO_BALL transitions
    ChaseMove --> ChaseRotate: not facing bal
    ChaseMove --> ChaseKick: close to ball
    ChaseMove --> ChaseDone: lost
    ChaseMove --> ChaseMove: not yet at ball

    %% KICK_BALL transitions
    ChaseKick --> ChaseRotate: after kick
    ChaseKick --> ChaseDone: lost

    %% DONE transitions
    ChaseDone --> ChaseRotate: ball found again, chase
    ChaseDone --> ChaseDone: ball still missing, rotate
