---
config:
  layout: elk
---
stateDiagram
    direction TB

    %% init
    state "Initial Setup (0)" as Init
    state "Check behaviour (1)" as Check

    %% normal play
    state "Rotate to target (10)" as RotatetoTarget
    state "Move to target (11)" as MovetoTarget
    state "Rotate to ball (12)" as RotatetoBall
    state "Move to ball (13)" as MovetoBall
    state "Kick ball (14)" as KickBall
    state "Normal play empty 1 (17)" as NormalPlayEmpty1
    state "Normal play empty 2 (18)" as NormalPlayEmpty2
    state "Normal play done (19)" as NormalPlayDone

    %% edge play
    state "Edge rotate to target (20)" as EdgeRotateTarget
    state "Edge move to target (21)" as EdgeMoveTarget
    state "Edge rotate to ball (22)" as EdgeRotateBall
    state "Edge move to ball (23)" as EdgeMoveBall
    state "Edge kick (24)" as EdgeKick
    state "Edge done (29)" as EdgeDone

    %% defend goal
    state "Defend rotate (30)" as DefendRotate
    state "Defend move (31)" as DefendMove
    state "Defend empty (32)" as DefendEmpty
    state "Defend done (39)" as DefendDone

    %% escape
    state "Escape rotate (40)" as EscapeRotate
    state "Escape move (41)" as EscapeMove
    state "Escape empty (42)" as EscapeEmpty
    state "Escape done (49)" as EscapeDone

    %% overall done
    state "Soccer done (99)" as SoccerDone


    %% transitions init
    [*] --> Init
    Init --> GoForwardRotate : identify agents

    Check --> RotatetoTarget: detected normal mode
    Check --> EdgeRotateTarget: detected edge mode
    Check --> DefendRotate: detected defend mode
    Check --> EscapeRotate: detected escape mode

    %% normal play
    RotatetoTarget --> RotatetoBall: reached target
    RotatetoTarget --> MovetoTarget: turned towards target
    RotatetoTarget --> RotatetoTarget: not towards target yet
    RotatetoTarget --> NormalPlayDone: lost 

    MovetoTarget --> RotatetoBall: reached target
    MovetoTarget --> RotatetoTarget: not facing target anymore
    MovetoTarget --> MovetoTarget: not yet at target
    MovetoTarget --> NormalPlayDone: lost 

    RotatetoBall --> MovetoBall: turned towards ball
    RotatetoBall --> RotatetoBall: not facing target yet
    RotatetoBall --> NormalPlayDone: lost 

    MovetoBall --> KickBall: close to ball
    MovetoBall --> RotatetoBall: not facing ball anymore
    MovetoBall --> NormalPlayDone: lost 

    KickBall --> NormalPlayDone: kicked ball

    NormalPlayDone --> NormalPlayDone: lost, rotating to search
    NormalPlayDone --> RotatetoTarget: found ball, chase


    %% edge play
    EdgeRotateTarget --> EdgeRotateBall: reached target
    EdgeRotateTarget --> EdgeMoveTarget: facing target
    EdgeRotateTarget --> EdgeRotateTarget: not facing target yet
    EdgeRotateTarget --> EdgeDone: lost
    
    EdgeMoveTarget --> EdgeRotateTarget: not facing target anymore
    EdgeMoveTarget --> EdgeRotateBall: reached target
    EdgeMoveTarget --> EdgeMoveTarget: not at target yet
    EdgeMoveTarget --> EdgeDone: lost

    EdgeRotateBall --> EdgeMoveBall: facing ball
    EdgeRotateBall --> EdgeRotateBall: not facing ball yet
    EdgeRotateBall --> EdgeDone: lost

    EdgeMoveBall --> EdgeRotateBall: not facing ball anymore
    EdgeMoveBall --> EdgeKick: at ball
    EdgeMoveBall --> EdgeMoveBall: not yet at ball
    EdgeMoveBall --> EdgeDone: lost

    EdgeKick --> EdgeDone: kicked

    EdgeDone --> EdgeDone: lost, rotate to search
    EdgeDone --> EdgeRotateTarget: ball found, go chase


    %% defense mode
    DefendRotate --> DefendMove: facing target
    DefendRotate --> DefendRotate: not facing target yet
    DefendRotate --> DefendDone: lost

    DefendMove --> DefendDone: defense target reached, or lost
    DefendMove --> DefendRotate: not facing defense target anymore
    DefendMove --> DefendMove: not reached defense target yet

    DefendDone --> DefendDone: lost, rotating to search
    DefendDone --> DefendRotate: found, go rotate towards defense target


    %% escape mode 
    EscapeRotate --> EscapeMove: facing target
    EscapeRotate --> EscapeRotate: not facing target yet
    EscapeRotate --> EscapeDone: lost

    EscapeMove --> EscapeDone: escape target reached, or lost
    EscapeMove --> EscapeRotate: not facing escape target anymore
    EscapeMove --> EscapeMove: not reached escape target yet

    EscapeDone --> EscapeDone: lost, rotating to search
    EscapeDone --> EscapeRotate: found, go rotate towards defense target


    %% play mode changes: 
    RotatetoTarget --> EscapeRotate: too close to opponent
    RotatetoTarget --> DefendRotate: opponent has ball and close to goal
    RotatetoTarget --> EdgeRotateTarget: ball at the edge

    MovetoTarget --> EscapeRotate: too close to opponent
    MovetoTarget --> DefendRotate: opponent has ball and close to goal
    MovetoTarget --> EdgeRotateTarget: ball at the edge

    RotatetoBall --> EscapeRotate: too close to opponent
    RotatetoBall --> DefendRotate: opponent has ball and close to goal
    RotatetoBall --> EdgeRotateTarget: ball at the edge

    MovetoBall --> EscapeRotate: too close to opponent
    MovetoBall --> DefendRotate: opponent has ball and close to goal
    MovetoBall --> EdgeRotateTarget: ball at the edge

    KickBall --> EscapeRotate: too close to opponent
    KickBall --> DefendRotate: opponent has ball and close to goal
    KickBall --> EdgeRotateTarget: ball at the edge

    NormalPlayDone --> EscapeRotate: too close to opponent
    NormalPlayDone --> DefendRotate: opponent has ball and close to goal
    NormalPlayDone --> EdgeRotateTarget: ball at the edge

    EdgeMoveTarget --> EscapeRotate: too close to opponent
    EdgeMoveTarget --> DefendRotate: opponent has ball and close to goal
    EdgeMoveTarget --> RotatetoTarget: ball no longer at edge

    EdgeRotateTarget --> EscapeRotate: too close to opponent
    EdgeRotateTarget --> DefendRotate: opponent has ball and close to goal
    EdgeRotateTarget --> RotatetoTarget: ball no longer at edge

    EdgeRotateBall --> EscapeRotate: too close to opponent
    EdgeRotateBall --> DefendRotate: opponent has ball and close to goal
    EdgeRotateBall --> RotatetoTarget: ball no longer at edge

    EdgeMoveBall --> EscapeRotate: too close to opponent
    EdgeMoveBall --> DefendRotate: opponent has ball and close to goal
    EdgeMoveBall --> RotatetoTarget: ball no longer at edge

    EdgeKick --> DefendRotate: opponent has ball and close to goal
    EdgeKick --> EscapeRotate: too close to opponent
    EdgeKick --> RotatetoTarget: ball no longer at edge

    EdgeDone --> EscapeRotate: too close to opponent
    EdgeDone --> DefendRotate: opponent has ball and close to goal
    EdgeDone --> RotatetoTarget: ball no longer at edge

    DefendRotate --> RotatetoTarget: opponent doesn't have the ball or not close to goal
    DefendRotate --> EscapeRotate: too close to opponent
    DefendRotate --> EdgeRotateTarget: ball at the edge

    DefendMove --> RotatetoTarget: opponent doesn't have the ball or not close to goal
    DefendMove --> EscapeRotate: too close to opponent
    DefendMove --> EdgeRotateTarget: ball at the edge

    DefendDone --> RotatetoTarget: opponent doesn't have the ball or not close to goal
    DefendDone --> EscapeRotate: too close to opponent
    DefendDone --> EdgeRotateTarget: ball at the edge

    EscapeRotate --> RotatetoTarget: opponent no longer too close
    EscapeRotate --> DefendRotate: opponent has ball and close to goal
    EscapeRotate --> EdgeRotateTarget: ball at the edge

    EscapeMove --> RotatetoTarget: opponent no longer too close
    EscapeMove --> DefendRotate: opponent has ball and close to goal
    EscapeMove --> EdgeRotateTarget: ball at the edge

    EscapeDone --> RotatetoTarget: opponent no longer too close
    EscapeDone --> DefendRotate: opponent has ball and close to goal
    EscapeDone --> EdgeRotateTarget: ball at the edge